# Basic; we don't need much, just to run sanity checks on database
# Ben Bond-Lamberty 2019-09-17

language: r

r_binary_packages:
  - ncdf4

r_packages:
  - sp

#install:
#    - Rscript R/install_packages.R

script:
  - Rscript R/srdb_check.R
